### ISSUE TITLE
Please respect our BSD 2-clause license

### ISSUE THREAD

**Issue by gimsieke** [nkutsche/css-model#1]
I noticed that [css3.ebnf](https://github.com/nkutsche/css-model/blob/main/src/main/resources/ebnf/css3.ebnf) is based on [CSS3.ebnf](https://github.com/transpect/css-tools/blob/master/ebnf-scheme/CSS3.ebnf) that may colleagues and I have been authoring for 8 years now. The [BSD 2-clause license of our css-tools repo](https://github.com/transpect/css-tools/blob/master/LICENSE.md) applies here.

I don’t know where the function [cssp:parse-css()](https://github.com/nkutsche/css-model/blob/a268721f52b192f863e0d145ef49b230c10ac082/src/main/resources/xsl/css3-model-parser.xsl#L19) is declared, but the processing of its output looks as if the output of a parser that is generated by REx from our EBNF is processed. If this function is supplied in a binary package, the licensing conditions for binary distributions apply.

In addition, the vocabulary of the CSS representation according to css-model.rnc partly resembles the output of our CSS parser. Although we didn’t supply a schema and the actual output is probably not identical, we’d expect that our project be mentioned as the basis or at least an inspiration for this vocabulary. 

The last point is optional, but we must insist that you respect the (liberal) licensing conditions that we attached to our intellectual property.

**Comment by nkutsche** [comment]
Oh damn, how embarrassing! You're absolutely right: your CSS3.ebnf was the basis for my css3.ebnf and the [css.xsl parser generated by ReX](https://github.com/nkutsche/css-model/blob/a268721f52b192f863e0d145ef49b230c10ac082/src/main/resources/xsl/css3.xsl). I can only assure you that it was pure sloppiness and not any bad intention.

A few words about the background/status of the project (not meant as an excuse): It was created as one of many small side projects for a larger main project I work on irregularly. In order to get a more stable state of development and to have less to do later when the main project is released, I pre-released and partially published all the side projects in one bigger action. Obviously I wasn't careful enough, sorry!

The main project is still far from a release. So from my side, I don't have the project in productive use anywhere yet. I don't think anyone else has used it, but of course I can't guarantee it anymore (and at the end it doesn't matter).

Here's what I'm doing now:

1. Delete the binaries of version 0.1.0 from our server.
2. Delete the release 0.1.0 on GitHub
3. Publish a release 0.1.1 with the following changes:
   * Adding your copyright statement in the EBNF file and in css.xsl.
   * Add your copyright statement to the project readme (the only documentation I have so far).
   * Add a notes about possible co-authorship of the schema (even though I'm not 100% with you on this)

Hope this is ok for you?
Sorry again!

**Comment by gimsieke** [comment]
Hi Nico, yes, that’s absolutely ok. And you need not mention us as schema co-authors.

**Comment by nkutsche** [comment]
Great! I did everything as described.

I'll keep [the note](https://github.com/nkutsche/css-model/tree/releases/v0.1.1#relaxng-schema) about the schema authorship to point out the similarity and the differences. Just to make it clear.

Thanks for reporting this issue!
